language: node_js
node_js:
  - "node"
cache: npm
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 2f3cd90faaea0b71129a0796f4d537b81cba6413
  local_dir: dist
  on:
    branch: master
